export const DATA_TYPE = {
  GENERAL: "GENERAL",
  PRICE: "PRICE",
  PROFILE: "PROFILE",
  STATISTICS: "STATISTICS",
  INCOME_STATEMENT: "INCOME_STATEMENT",
  INCOME_STATEMENT_HISTORY: "INCOME_STATEMENT_HISTORY",
  INCOME_STATEMENT_QUARTERLY: "INCOME_STATEMENT_QUARTERLY",
  INCOME_STATEMENT_QUARTERLY_HISTORY: "INCOME_STATEMENT_QUARTERLY_HISTORY",
  BALANCE_SHEET: "BALANCE_SHEET",
  BALANCE_SHEET_HISTORY: "BALANCE_SHEET_HISTORY",
  BALANCE_SHEET_QUARTERLY: "BALANCE_SHEET_QUARTERLY",
  BALANCE_SHEET_QUARTERLY_HISTORY: "BALANCE_SHEET_QUARTERLY_HISTORY",
  CASH_FLOW: "CASH_FLOW",
  CASH_FLOW_HISTORY: "CASH_FLOW_HISTORY",
  CASH_FLOW_QUARTERLY: "CASH_FLOW_QUARTERLY",
  CASH_FLOW_QUARTERLY_HISTORY: "CASH_FLOW_QUARTERLY_HISTORY",
};

export const DISABLE_CACHE_BY_DATA_TYPE = {
  [DATA_TYPE.PRICE]: true,
};

export const YAHOO_REQUEST = {
  FINANCIAL: "Financial",
};

export const DATA_TYPES_BY_REQUEST = {
  [YAHOO_REQUEST.FINANCIAL]: [
    DATA_TYPE.INCOME_STATEMENT,
    DATA_TYPE.INCOME_STATEMENT_HISTORY,
    DATA_TYPE.INCOME_STATEMENT_QUARTERLY,
    DATA_TYPE.INCOME_STATEMENT_QUARTERLY_HISTORY,
    DATA_TYPE.BALANCE_SHEET,
    DATA_TYPE.BALANCE_SHEET_HISTORY,
    DATA_TYPE.BALANCE_SHEET_QUARTERLY,
    DATA_TYPE.BALANCE_SHEET_QUARTERLY_HISTORY,
    DATA_TYPE.CASH_FLOW,
    DATA_TYPE.CASH_FLOW_HISTORY,
    DATA_TYPE.CASH_FLOW_QUARTERLY,
    DATA_TYPE.CASH_FLOW_QUARTERLY_HISTORY,
    DATA_TYPE.GENERAL,
    DATA_TYPE.PRICE,
  ],
};

export const REQUESTS_BY_DATA_TYPE = Object.entries(
  DATA_TYPES_BY_REQUEST
).reduce((acc, [request, types]) => {
  types.forEach((type) => {
    if (!acc[type]) acc[type] = [];
    acc[type].push(request);
  });
  return acc;
}, {});
